### ISSUE TITLE
Sending "List my subscriptions" right after being authenticated should not ask user to select a subscription

### ISSUE THREAD

**Issue by ejadib** [dtzar/AzureBot#36]
Listing the subscriptions doesn't depend on having a subscription selected.

![image](https://cloud.githubusercontent.com/assets/307826/15429114/91498394-1e75-11e6-94fe-e8948bce1df9.png)

**Comment by f2bo** [comment]
This is no longer an issue since the user already selects a subscription when the conversation starts. Closing.
