### ISSUE TITLE
What should happen when logging in a slack channel?

### ISSUE THREAD

**Issue by JuanAr** [dtzar/AzureBot#46]
Scenario: In a slack channel, a user initiates a conversation with the AzureBot and, currently, the login link is sent to the channel. Since all joined users receives all messages, a different user could use the link and share their credentials. While this could be useful it is not the expected behavior.

Proposals:
- Send Login link in a new private conversation to the initiating user (we need to check if it's doable)

**Comment by dtzar** [comment]
DM'ing people the auth link would be a great option if possible

**Comment by dtzar** [comment]
We have a fix for this which utilizes a browser code method to address it.  Will implement in future version of the AzureBot.
