### ISSUE TITLE
Authentication timeout not handled

### ISSUE THREAD

**Issue by dtzar** [dtzar/AzureBot#56]
If you authenticate and then come back at a later time, it doesn't gracefully give you an answer that you need to re-authenticate.  For instance, on Slack it simply says: "​Sorry, AzureBot is having a problem responding right now."

**Comment by ejadib** [comment]
Related to #32

**Comment by JuanAr** [comment]
Some additional info from [here](http://www.cloudidentity.com/blog/2015/03/20/azure-ad-token-lifetime/)

1. - Access-Token expires in 1 hour
2. - Refresh Token expires in 14 days
3. - Using the refresh-token for a maximum period of time of 90 days
4. - None of these settings seems configurable
5. - Refresh tokens can be invalidated at ANY time

Item #32 focus on (1) and (2). There nothing to do with (4).

We should tackle (3) and (5) as part of this issue #56. Once we hit the refresh limit or the token gets invalidated we should ask the user to log in again.

**Comment by dtzar** [comment]
I'm thinking we should start with the Access-Token (what it is now I assume) and then handle the 1 hour timeout when the user tries to interact again - ask them something like "You're Azure authentication is expired. Would you like to renew your access token for another hour or 14 more days?"

Probably a separate "enhancement" would be to allow the user to revoke/invalidate their token.

**Comment by ejadib** [comment]
Thanks @dtzar. For (1) and (2) we are trying to acquire a new token silently so it's really transparent for the user. In this way if the user has sent a message and the token expired, it can be renewed and the operation executed without any user interaction. We could potentially go with a Prompt though. 

Regarding the hour or 14 more days, we will need to find out the best way to relaunch the Auth dialog.
