### ISSUE TITLE
Make switch to different subscription experience better

### ISSUE THREAD

**Issue by dtzar** [dtzar/AzureBot#76]
"switch to myinternal01 subscription"
Prompts to select from a list of ALL subscriptions. 

Ideal – You should have matched that myinternal01 exact name of one of my subscriptions
Fallback – You should have filtered the list of subscriptions by the terms I gave you

**Comment by ejadib** [comment]
This should be already fixed. Are you experiencing this with the current version of the bot?

**Comment by dtzar** [comment]
Sorry I can see it works now.

**Comment by ejadib** [comment]
We noticed that it's failing if you use the wrong casing, so we will fix that.

**Comment by ejadib** [comment]
Close since #80 was opened
