### ISSUE TITLE
Use the LUIS score when processing an action

### ISSUE THREAD

**Issue by f2bo** [dtzar/AzureBot#86]
If a user expresses an intent that is not defined by the LUIS model, it can be mistakenly mapped to one of the methods in the ActionDialog. Currently, the implementation assumes that the intent was interpreted correctly, which may lead to unexpected results. For example, see #78.

The LuisResult includes a score that expresses the confidence in the result. There are scores for both intents and entities. We could take advantage of the scores to decide whether to execute the corresponding action or ask for confirmation. For example, if the score is below a certain threshold, reply with a message saying "I didn't understand. Did you mean XXXX?"

**Comment by dtzar** [comment]
This issue was moved to Microsoft/AzureBot#5
